name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'frontend/.nvmrc'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Create test environment file
        run: |
          echo "VITE_API_URL=http://localhost:8000/api/v1" > .env.test
          echo "VITE_SUPABASE_URL=https://example.supabase.co" >> .env.test
          echo "VITE_SUPABASE_ANON_KEY=test-supabase-key" >> .env.test
        working-directory: frontend
      - name: Install dependencies
        run: npm install
        working-directory: frontend
      - name: Lint
        run: npm run lint
        working-directory: frontend
      - name: Type check
        run: npm run typecheck
        working-directory: frontend
      - name: Test
        run: |
          export NODE_OPTIONS="--max-old-space-size=8192"
          npm test -- --coverage --no-threads
        working-directory: frontend
